backend:
  name: github
  repo: ChrisPublic-git/note-from-dystopia
  branch: main
  base_url: https://vercel.app
  auth_endpoint: api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "notes"
    label: "Notes"
    folder: "/"
    extension: "html"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body Content", name: "body", widget: "markdown" }
