backend:
  name: github
  repo: ChrisPublic-git/note-from-dystopia
  branch: main # Change this to match the exact branch you select in Porkbun

media_folder: "notes/assets/images"
public_folder: "/assets/images"

collections:
  - name: "notes"
    label: "Notes"
    folder: "notes" # Assumes your note files live in the notes subdirectory
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
